-- 008: 멀티사이트 지원을 위한 site_id 추가
-- 모든 테이블에 site_id 컬럼 추가 (기본값 0)

ALTER TABLE TB_CONTENT ADD COLUMN site_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TB_SESSION ADD COLUMN site_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TB_MESSAGE ADD COLUMN site_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TB_SESSION_CONTENT ADD COLUMN site_id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE TB_QUIZ ADD COLUMN site_id INTEGER NOT NULL DEFAULT 0;

-- site_id 인덱스
CREATE INDEX IF NOT EXISTS idx_content_site_id ON TB_CONTENT(site_id);
CREATE INDEX IF NOT EXISTS idx_session_site_id ON TB_SESSION(site_id);
CREATE INDEX IF NOT EXISTS idx_message_site_id ON TB_MESSAGE(site_id);
CREATE INDEX IF NOT EXISTS idx_session_content_site_id ON TB_SESSION_CONTENT(site_id);
CREATE INDEX IF NOT EXISTS idx_quiz_site_id ON TB_QUIZ(site_id);
